# Generated by Django 5.2.7 on 2025-10-26 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='data_Criacao',
            new_name='data_criacao',
        ),
    ]
